routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();

Route::group(['middleware' => ['auth']], function () {
Route::get('/', function () {
    return view('home');
});



Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::resource('posts', App\Http\Controllers\PostController::class);
Route::get('/posts/{post}/approve', [App\Http\Controllers\PostController::class, 'approval'])->name('post.approval');
Route::post('/posts/{post}', [App\Http\Controllers\PostController::class, 'approve'])->name('post.approve');
});

app/Models/Post.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    use HasFactory;

 /**
     * The attributes that are mass assignable.
     *
     * @var string[]
     */
    protected $fillable = [
        'body',
        'category',
        'status'
    ];
    public function user()
    {
        return $this->belongsTo('App\Models\User', 'user_id');
    }
    public function category()
    {
        return $this->belongsTo('App\Models\Category', 'category_id');
    }

}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use App\Models\Post;
use App\Models\Category;
use Illuminate\Http\Request;

class PostController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $posts = Post::all();
        $pending_posts = Post::all()->where('status','=','pending');
        $published_posts = Post::all()->where('status','=','published');
        return view('dashboard.posts.index',compact('posts','published_posts','pending_posts'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories = Category::all();
        return view('dashboard.posts.create', compact('categories'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validatedData = $request->validate([
            'body'           => 'required',
            'category'           => 'required',
        ]);

        $user = auth()->user();
        $post = new Post();
        $post->body = $request->input('body');
        $post->category_id = $request->input('category');
        $post->status = 'pending';
        $post->user_id = $user->id;
        $post->save();
        $request->session()->flash('message', 'Ticker Post Added!');
        return redirect()->route('posts.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function show(Post $post)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $categories = Category::all();
        $post = Post::find($id);
        return view('dashboard.posts.edit',compact('categories','post'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $validatedData = $request->validate([
            'body'           => 'required',
            'category'           => 'required',
        ]);

        $post = Post::find($id);
        $post->body = $request->input('body');
        $post->category_id = $request->input('category');
        $post->status = $request->input('status');
        $post->save();
        $request->session()->flash('message', 'Ticker Post Status Updated!');
        return redirect()->route('posts.index');
    }

    public function approval($id)
    {
        $categories = Category::all();
        $post = Post::find($id);
        return view('dashboard.posts.approve',compact('categories','post'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function approve(Request $request, $id)
    {
        $validatedData = $request->validate([
            'body'           => 'required',
            'category'           => 'required',
            'status'            => 'required'
        ]);

        $post = Post::find($id);
        $post->body = $request->input('body');
        $post->category_id = $request->input('category');
        $post->status = $request->input('status');
        $post->save();
        $request->session()->flash('message', 'Ticker Post  Updated!');
        return redirect()->route('posts.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function destroy(Post $post)
    {
        //
    }
}

resources/views/dashboard/posts/approve.blade.php
@extends('layouts.app')
@section('content')
<div class="page-heading">
    <div class="page-title">
        <div class="row">
            <div class="col-12 col-md-6 order-md-1 order-last">
                <h3>Input</h3>
                <p class="text-subtitle text-muted">Give textual form controls like input upgrade with custom styles,
                    sizing, focus states, and more.</p>
            </div>
            <div class="col-12 col-md-6 order-md-2 order-first">
                <nav aria-label="breadcrumb" class="breadcrumb-header float-start float-lg-end">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="index.html">Dashboard</a></li>
                        <li class="breadcrumb-item active" aria-current="page">Input</li>
                    </ol>
                </nav>
            </div>
        </div>
        <div class="row">
            @if (Session::has('message'))
                <div class="container">
                    <div class="alert alert-success alert-dismissible" role="alert">
                        <div class="alert-icon">
                            <i class="far fa-fw fa-bell"></i>
                        </div>
                        <div class="alert-message">
                            <strong> {{ session('message') }}</strong>
                        </div>

                        <button type="button" class="btn-close btn-close-white" data-bs-dismiss="alert"
                            aria-label="Close"></button>
                    </div>
                </div>
            @endif
            @if ($errors->any())
                <div class="container">
                    <div class="alert alert-danger alert-dismissible" role="alert">
                        @foreach ($errors->all() as $error)
                            <div class="alert-icon">
                                <i class="far fa-fw fa-bell"></i>
                            </div>
                            <div class="alert-message">
                                <strong> {{ $error }}</strong>
                            </div>

                            <button type="button" class="btn-close btn-close-white" data-bs-dismiss="alert"
                                aria-label="Close"></button>
                        @endforeach
                    </div>
                </div>
            @endif
        </div>
    </div>
    <section class="section">
        <div class="card">
            <div class="card-header">
                <h4 class="card-title">Basic Inputs</h4>
            </div>
            <form method="POST" action="{{ route('post.approve', $post->id) }}">
                @method('PUT')
                @csrf
            <div class="card-body">
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label for="basicInput">Ticker Item</label>
                            <input name="body" value="{{$post->body}}" type="text" class="form-control" id="body" placeholder="Enter ticker Item">
                        </div>
                        <div class="col-md-6">
                        <div class="form-group">
                            <label for="basicInput">Category</label>
                            <select class="form-select" name="category" id="basicSelect">
                               @foreach ( $categories as $category )
                               <option value="{{ $category->id }}" @if($post->category->id === $category->id) selected='selected' @endif>{{ $category->name }}</option>
                               @endforeach
                            </select>
                        </div>
                        </div>

                    </div>
                </div>
                <div class="row">
                        <div class="col-md-6">
                        <div class="form-group">
                            <label for="basicInput">Status</label>
                            <select class="form-select" name="status" id="basicSelect">
                               <option value="pending" @if($post->status === 'pending') selected='selected' @endif>Pending</option>
                               <option value="published" @if($post->status === 'published') selected='selected' @endif>Published</option>
                            </select>
                        </div>
                        </div>

                    </div>
                <div class="row">
                    <div class="mb-3 col-md-6">
                        <a href="{{ route('posts.index') }}" style="background-color: rgb(53, 54, 55) !important;"
                            class="btn btn-primary">Cancel</a>
                    </div>
                    <div class="mb-3 col-md-1">
                        <button style="background-color: rgb(37, 38, 38) !important;" type="submit"
                            class="btn btn-primary">Submit</button>
                    </div>
                </div>
            </div>
            </form>
        </div>
    </section>



</div>
@endsection
@section('javascript')
@endsection

resources/views/dashboard/posts/create.blade.php
@extends('layouts.app')
@section('content')
<div class="page-heading">
    <div class="page-title">
        <div class="row">
            <div class="col-12 col-md-6 order-md-1 order-last">
                <h3>Input</h3>
                <p class="text-subtitle text-muted">Give textual form controls like input upgrade with custom styles,
                    sizing, focus states, and more.</p>
            </div>
            <div class="col-12 col-md-6 order-md-2 order-first">
                <nav aria-label="breadcrumb" class="breadcrumb-header float-start float-lg-end">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="index.html">Dashboard</a></li>
                        <li class="breadcrumb-item active" aria-current="page">Input</li>
                    </ol>
                </nav>
            </div>
        </div>
        <div class="row">
            @if (Session::has('message'))
                <div class="container">
                    <div class="alert alert-success alert-dismissible" role="alert">
                        <div class="alert-icon">
                            <i class="far fa-fw fa-bell"></i>
                        </div>
                        <div class="alert-message">
                            <strong> {{ session('message') }}</strong>
                        </div>

                        <button type="button" class="btn-close btn-close-white" data-bs-dismiss="alert"
                            aria-label="Close"></button>
                    </div>
                </div>
            @endif
            @if ($errors->any())
                <div class="container">
                    <div class="alert alert-danger alert-dismissible" role="alert">
                        @foreach ($errors->all() as $error)
                            <div class="alert-icon">
                                <i class="far fa-fw fa-bell"></i>
                            </div>
                            <div class="alert-message">
                                <strong> {{ $error }}</strong>
                            </div>

                            <button type="button" class="btn-close btn-close-white" data-bs-dismiss="alert"
                                aria-label="Close"></button>
                        @endforeach
                    </div>
                </div>
            @endif
        </div>
    </div>
    <section class="section">
        <div class="card">
            <div class="card-header">
                <h4 class="card-title">Basic Inputs</h4>
            </div>
            <form method="POST" enctype="multipart/form-data" action="{{ route('posts.store') }}">
                @csrf
            <div class="card-body">
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label for="basicInput">Ticker Item</label>
                            <input name="body" type="text" class="form-control" id="body" placeholder="Enter ticker Item">
                        </div>
                        <div class="col-md-6">
                        <div class="form-group">
                            <label for="basicInput">Category</label>
                            <select class="form-select" name="category" id="basicSelect">
                               @foreach ( $categories as $category )
                               <option value="{{$category->id }}">{{ $category->name}}</option>
                               @endforeach
                            </select>
                        </div>
                        </div>

                    </div>
                </div>
                <div class="row">
                    <div class="mb-3 col-md-6">
                        <a href="{{ route('posts.index') }}" style="background-color: rgb(53, 54, 55) !important;"
                            class="btn btn-primary">Cancel</a>
                    </div>
                    <div class="mb-3 col-md-1">
                        <button style="background-color: rgb(37, 38, 38) !important;" type="submit"
                            class="btn btn-primary">Submit</button>
                    </div>
                </div>
            </div>
            </form>
        </div>
    </section>



</div>
@endsection
@section('javascript')
<script src="assets/vendors/jquery/jquery.min.js"></script>
<script src="assets/vendors/jquery-datatables/jquery.dataTables.min.js"></script>
<script src="assets/vendors/jquery-datatables/custom.jquery.dataTables.bootstrap5.min.js"></script>
<script src="assets/vendors/fontawesome/all.min.js"></script>
<script>
    // Jquery Datatable
    let jquery_datatable = $("#table1").DataTable()
</script>
@endsection

resources/views/dashboard/posts/edit.blade.php
@extends('layouts.app')
@section('content')
<div class="page-heading">
    <div class="page-title">
        <div class="row">
            <div class="col-12 col-md-6 order-md-1 order-last">
                <h3>Input</h3>
                <p class="text-subtitle text-muted">Give textual form controls like input upgrade with custom styles,
                    sizing, focus states, and more.</p>
            </div>
            <div class="col-12 col-md-6 order-md-2 order-first">
                <nav aria-label="breadcrumb" class="breadcrumb-header float-start float-lg-end">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="index.html">Dashboard</a></li>
                        <li class="breadcrumb-item active" aria-current="page">Input</li>
                    </ol>
                </nav>
            </div>
        </div>
        <div class="row">
            @if (Session::has('message'))
                <div class="container">
                    <div class="alert alert-success alert-dismissible" role="alert">
                        <div class="alert-icon">
                            <i class="far fa-fw fa-bell"></i>
                        </div>
                        <div class="alert-message">
                            <strong> {{ session('message') }}</strong>
                        </div>

                        <button type="button" class="btn-close btn-close-white" data-bs-dismiss="alert"
                            aria-label="Close"></button>
                    </div>
                </div>
            @endif
            @if ($errors->any())
                <div class="container">
                    <div class="alert alert-danger alert-dismissible" role="alert">
                        @foreach ($errors->all() as $error)
                            <div class="alert-icon">
                                <i class="far fa-fw fa-bell"></i>
                            </div>
                            <div class="alert-message">
                                <strong> {{ $error }}</strong>
                            </div>

                            <button type="button" class="btn-close btn-close-white" data-bs-dismiss="alert"
                                aria-label="Close"></button>
                        @endforeach
                    </div>
                </div>
            @endif
        </div>
    </div>
    <section class="section">
        <div class="card">
            <div class="card-header">
                <h4 class="card-title">Basic Inputs</h4>
            </div>
            <form method="POST" enctype="multipart/form-data" action="{{ route('posts.update', $post->id) }}">
                @method('PUT')
                @csrf
            <div class="card-body">
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label for="basicInput">Ticker Item</label>
                            <input name="body" value="{{$post->body}}" type="text" class="form-control" id="body" placeholder="Enter ticker Item">
                        </div>
                        <div class="col-md-6">
                        <div class="form-group">
                            <label for="basicInput">Category</label>
                            <select class="form-select" name="category" id="basicSelect">
                               @foreach ( $categories as $category )
                               <option value="{{ $category->id }}" @if($post->category->id === $category->id) selected='selected' @endif>{{ $category->name }}</option>
                               @endforeach
                            </select>
                        </div>
                        </div>

                    </div>
                </div>
                <div class="row">
                    <div class="mb-3 col-md-6">
                        <a href="{{ route('posts.index') }}" style="background-color: rgb(53, 54, 55) !important;"
                            class="btn btn-primary">Cancel</a>
                    </div>
                    <div class="mb-3 col-md-1">
                        <button style="background-color: rgb(37, 38, 38) !important;" type="submit"
                            class="btn btn-primary">Submit</button>
                    </div>
                </div>
            </div>
            </form>
        </div>
    </section>



</div>
@endsection
@section('javascript')
@endsection

resources/views/dashboard/posts/index.blade.php
@extends('layouts.app')
@section('content')
<div class="page-heading">
    <div class="page-title">
        <div class="row">
            <div class="col-12 col-md-6 order-md-1 order-last">
                <h3>Ticker  Items</h3>
            </div>
        </div>
    </div>

    <!-- Basic Tables start -->
    <section class="section">
        <div class="card">
            <div class="card-header">
                All Posts
                <a class="btn btn-primary" href="{{route('posts.create') }}" >Add a New Post <i class="fa fa-plus"></i></a>
            </div>
            <div class="card-body">
												<div class="table-responsive">
                <table class="table table-responsive" id="table1">
                    <thead>
                        <tr>
                            <th> #</th>
                            <th>Ticker Item</th>
                            <th>Category</th>
                            <th>Author</th>
                            <th>Status</th>
                        </tr>
                    </thead>
                    <tbody>
                        @if (request()->query("filter") === 'pending' )
                        @foreach ($pending_posts as $post )
                          <tr>
                            <td> @if (Auth::user()->role ==='administrator')
                                <a href="{{route('post.approval',$post->id )}}">Approve/Edit</a>

                            @elseif (Auth::user()->role ==='editor')
                            <a href="{{route('post.approval',$post->id )}}">Approve/Edit</a>
                            @else
                            <a href="{{route('posts.edit',$post->id )}}">Edit</a>
                            @endif </td>
                            <td>{{$post->body}}</td>
                            <td>{{$post->category->name}}</td>
                            <td>{{$post->user->name}}</td>
                            <td>
                                @if ($post->status === 'published')
                                <span class="badge bg-success">{{$post->status}}</span>
                                @else
                                <span class="badge bg-info">{{$post->status}}</span>
                                @endif
                            </td>
                        </tr>
                        @endforeach
                        @elseif (request()->query("filter") === 'published' )
                        @foreach ($published_posts as $post )
                        <tr>
                          <td> @if (Auth::user()->role ==='administrator')
                              <a href="{{route('post.approval',$post->id )}}">Approve/Edit</a>

                          @elseif (Auth::user()->role ==='editor')
                          <a href="{{route('post.approval',$post->id )}}">Approve/Edit</a>
                          @else
                          <a href="{{route('posts.edit',$post->id )}}">Edit</a>
                          @endif </td>
                          <td>{{$post->body}}</td>
                          <td>{{$post->category->name}}</td>
                          <td>{{$post->user->name}}</td>
                          <td>
                              @if ($post->status === 'published')
                              <span class="badge bg-success">{{$post->status}}</span>
                              @else
                              <span class="badge bg-info">{{$post->status}}</span>
                              @endif
                          </td>
                      </tr>
                      @endforeach

                      @else
                      @foreach ($posts as $post )
                        <tr>
                          <td> @if (Auth::user()->role ==='administrator')
                              <a href="{{route('post.approval',$post->id )}}">Approve/Edit</a>

                          @elseif (Auth::user()->role ==='editor')
                          <a href="{{route('post.approval',$post->id )}}">Approve/Edit</a>
                          @else
                          <a href="{{route('posts.edit',$post->id )}}">Edit</a>
                          @endif </td>
                          <td>{{$post->body}}</td>
                          <td>{{$post->category->name}}</td>
                          <td>{{$post->user->name}}</td>
                          <td>
                              @if ($post->status === 'published')
                              <span class="badge bg-success">{{$post->status}}</span>
                              @else
                              <span class="badge bg-info">{{$post->status}}</span>
                              @endif
                          </td>
                      </tr>
                      @endforeach
                      @endif

                    </tbody>
                </table>
            </div>
        </div>
</div>


    </section>
    <!-- Basic Tables end -->
</div>
@endsection
@section('javascript')
<script src="assets/vendors/jquery/jquery.min.js"></script>
<script src="assets/vendors/jquery-datatables/jquery.dataTables.min.js"></script>
<script src="assets/vendors/jquery-datatables/custom.jquery.dataTables.bootstrap5.min.js"></script>
<script src="assets/vendors/fontawesome/all.min.js"></script>
<script>
    // Jquery Datatable
    let jquery_datatable = $("#table1").DataTable()
</script>
@endsection